-- NOTE: A large portion of this file was generated by AI

module Test.Groups.Module

import Data.LLVM
import Data.LLVM.IR
import Data.LLVM.Write.Text.Encode
import Data.LLVM.Class
import Test.Helper
import Data.LLVM.Write.Foreign

%hide Data.LLVM.Ops.Core.emptyModule

export
moduleTests : IO ()
moduleTests = do
    pure ()